-   id: clang-format
    name: clang-format
    description: Format files with ClangFormat.
    entry: ./bin/clang-format
    language: script
    files: \.(c|cc|cxx|cpp|h|tcc)$
    args: ['-fallback-style=none', '-i']
